name: Update Import
on:
 schedule:
  - cron: '35 0 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: atactions/import-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          url: 'https://gopkg.in/alecthomas/kingpin.v2'
